### ISSUE TITLE
Not working on Mac Intel and M1

### ISSUE THREAD

**Issue by klauskobald** [norihiro/obs-face-tracker#101]
I tried several locations to install it:
~/Library/Application Support/obs-studio/Plugins
Also the application content/plugins

But the plugin does not show up under filters. Neither on my old macbook 2014 nor on my new M1 Macbook.
Any ideas?

**Comment by norihiro** [comment]
Could you provide a log file? It shows whether the plugin is loaded or failed, and reasons if failed.
- In OBS select Help > Log Files > Upload Current Log File.
- Click Copy URL and then paste the link here.

**Comment by jeremiasmanninen** [comment]
Exactly same problem here with my M1 Macbook Air.
Here is a log file: https://obsproject.com/logs/JEwCP0jOOs9tYZpM

Seems like it could not load because I am running an Arm build of OBS on the M1 chip.
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/81366427/156922252-35407af1-56da-4a21-87ef-bb70771dc8b1.png">

I try to test it later this day on another Mac with x86_64 intel processor.

**Comment by norihiro** [comment]
@jeremiasmanninen,
This plugin does not have binary for ARM so that it cannot work with the native code for M1. I'm waiting obs-plugintemplate support M1 build script, which will arrive before OBS version 28.

**Comment by DanielsCode** [comment]
+1

**Comment by norihiro** [comment]
Close due to no activities and insufficient information.
Note that the original reporter was not claiming the plugin failed to run on the Arm architecture but failing on x86_64 architecture. Hence, jeremiasmanninen's comment is not related to the issue.
