### ISSUE TITLE
There may be some problem when showing or hiding switch in the group. 

### ISSUE THREAD

**Issue by iesvme** [norihiro/obs-face-tracker#14]
There may be some problem when showing or hiding switch in the group. The Preview screen will cause not to work. However, When restarting the OBS 27.01, The Program screen won't work in stead.

![image](https://user-images.githubusercontent.com/16969250/121766317-82c47700-cb83-11eb-9062-d0c3f875f70a.png)
![image](https://user-images.githubusercontent.com/16969250/121767370-60822780-cb8a-11eb-8268-2ed4e4eb7d13.png)

**Comment by norihiro** [comment]
I'm sorry that I couldn't fully catch how your problem was made.
It looks like your scene in preview has a group and camera on the group like below. How the other scene is configured?
And, how is your transition settings? The settings will appear by clicking a gear icon at the right of Transition button. Did you enable `Duplicate Scene` and/or `Duplicate Sources`?

My recommended usage is having two scenes; 'Scene 1' and 'Scene 2'. In this configuration, we don't need to switch the effect but just change the source to enable/disable Face Tracker.
- Scene 1 (This is a plain scene without face tracking)
  - Camera
   ![ft-scene1](https://user-images.githubusercontent.com/780600/121767934-67169c00-cb96-11eb-87fa-7a8191964408.png)
- Scene 2 (This is a scene with face tracking)
  - Group-tracker (This group has Face Tracker effect filter)
    - Camera (duplicated from that in Scene 1.)
   ![ft-scene2](https://user-images.githubusercontent.com/780600/121767933-65e56f00-cb96-11eb-81d9-07cf37156059.png)

**Comment by iesvme** [comment]
Sorry for my poor English!

https://user-images.githubusercontent.com/16969250/121768510-29634480-cb91-11eb-9d59-8cb7b9c7381d.mp4

**Comment by norihiro** [comment]
> I'm sorry that I couldn't fully catch how your problem was made.
Don't worry. I'm also not a native English speaker. I appreciate your report.

Your step is as below.
1. `Group` has the Face Tracker filter.
2. Change crop setting by Alt+drag.
3. Transition
4. Hide `Group`
5. Transition
6. Show `Group`
7. Transition
8. Reset crop
9. Transition
10. Hide
11. Transition
12. Show
13. Transition
   At this time, the face tracker does not work on Preview.
14. Change crop
15. Transition
   Still face tracker does not work on Preview.

There seems two issues.
- When transit to Program, Face Tracker starts from the initial condition. I don't like this behavior.
- Keep hiding and showing, Face Tracker becomes not working. (I think the crop by mouse does not affect Face Tracker because the crop by mouse is processed after Face Tracker.)

**Comment by norihiro** [comment]
I released [version 0.1.1](https://github.com/norihiro/obs-face-tracker/releases/tag/0.1.1).
Would you try this. If the problem still exists, please feel free to reopen this ticket.

**Comment by iesvme** [comment]
It works very well now. Thank you so so much!!!
