### ISSUE TITLE
Tracking face on 16:9 video and converting to 9:16 without zooming

### ISSUE THREAD

**Issue by jeremiasmanninen** [norihiro/obs-face-tracker#61]
Hello there!

I am planning to use this plugin to convert the 16:9 live video to 9:16 for streaming to Instagram. (I am also streaming at 16:9 on another computer to other platforms.) So it would be great to add a 9:16 aspect ratio to the existing list of the final video dimensions. Now the closest aspect ratio to portrait is 4:3. It would be also great to add a possibility not to zoom at all (now the minium zoom is 0,10). With these 2 little improvements, I guess this plugin could serve very well on purposes when wanting to track a face in landscape video to convert to portrait video.

Thank you very much for developing this plugin!
Jeremias

**Comment by norihiro** [comment]
>  it would be great to add a 9:16 aspect ratio to the existing list

The new aspect `9:16` will be supported by the next release. For now, you can manually input `9:16` to the combo-box.

> It would be also great to add a possibility not to zoom at all (now the minium zoom is 0,10)

Instead of `Zoom`, you can set `Scale max` to `1.0` so that it won't scale at all.
However, if you just want to change the aspect, since it will consume your CPU, I recommend to use `Edit Transform` feature in OBS Studio. Please set `Crop Left` and `Crop Right` so that your video becomes 9:16.
